version: '3'

services:
  frontend:
    image: agrawaldev1112/online_judge:frontend_1.0.0
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    image: agrawaldev1112/online_judge:backend_1.0.0
    ports:
      - 5000:5000